spring.application.name=connect
spring.datasource.url=jdbc:postgresql://localhost:5432/connect_uerj_db
spring.datasource.username=postgres
spring.datasource.password=peco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true